# Generated by Django 5.1.1 on 2024-09-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('Sumava', 'Šumava'), ('CB', 'Českobudějovicko'), ('Strak', 'Strakonicko'), ('Krum', 'Krumlovsko'), ('Treb', 'Třeoňsko')], max_length=128),
        ),
    ]
