# Generated by Django 5.1.1 on 2024-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0008_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='delivery_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
