# Generated by Django 5.1.1 on 2024-09-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0009_region_delivery_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='car_type',
        ),
        migrations.AddField(
            model_name='drivercar',
            name='salary',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='region',
            name='km',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
