# Generated by Django 5.1.1 on 2024-09-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0010_rename_type_car_car_type_drivercar_salary_region_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
