# Generated by Django 5.1.1 on 2024-09-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0011_car_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='deliver_time',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
