# Generated by Django 5.1.1 on 2024-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0012_region_deliver_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivercar',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='drivercar',
            name='salary',
        ),
        migrations.AddField(
            model_name='driver',
            name='salary',
            field=models.IntegerField(default=250),
        ),
    ]
