# Generated by Django 5.1.1 on 2024-09-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0013_remove_drivercar_driver_remove_drivercar_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='salary',
        ),
        migrations.AddField(
            model_name='product',
            name='salary',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='product',
            name='seeding_time',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='product',
            name='watering_time',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='ProductCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kw_price', models.IntegerField(default=4)),
                ('watts', models.IntegerField(default=60)),
                ('lighting_hours', models.IntegerField(default=18)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_app.driver')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden_app.product')),
            ],
        ),
    ]
