# Generated by Django 5.1.1 on 2024-09-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0015_remove_product_salary_productcost_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcost',
            name='driver',
        ),
    ]
