# Generated by Django 5.1.1 on 2024-09-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0017_region_preparing_time_deliverycost_delete_drivercar'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='salary',
            field=models.IntegerField(default=250),
        ),
    ]
