# Generated by Django 5.1.1 on 2024-09-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0018_driver_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycost',
            name='fuel_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverycost',
            name='salary_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverycost',
            name='total_delivery_costs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverycost',
            name='total_products_costs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_costs', to='garden_app.region'),
        ),
    ]
