# Generated by Django 5.1.1 on 2024-09-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0019_deliverycost_fuel_cost_deliverycost_salary_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycost',
            name='total_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
