# Generated by Django 5.1.1 on 2024-09-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0020_deliverycost_total_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycost',
            name='margin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
