# Generated by Django 5.1.1 on 2024-09-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0021_deliverycost_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcost',
            name='total_product_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
