# Generated by Django 5.1.1 on 2024-09-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0022_productcost_total_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcost',
            name='total_product_cost',
            field=models.FloatField(),
        ),
    ]
