# Generated by Django 5.1.1 on 2024-09-23 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0024_alter_car_capacity_alter_car_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)]),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='fuel_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='fuel_price',
            field=models.PositiveIntegerField(default=32, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='deliverycost',
            name='salary_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
