# Generated by Django 5.1.1 on 2024-10-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0025_alter_car_year_alter_deliverycost_fuel_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcost',
            name='total_product_cost',
            field=models.FloatField(null=True),
        ),
    ]
